repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
        require_serial: true
        types: [python]

      - id: ruff-check
        name: Ruff Lint
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        require_serial: true
        types: [python]

      - id: mypy
        name: Mypy Type Check
        entry: uv run mypy .
        language: system
        pass_filenames: false
        require_serial: true
        types: [python]

      - id: prettier
        name: Prettier auto-formatting
        entry: npx prettier --check
        language: system
        types: [yaml]
